[package]
name = "oxytail-theme-dark"
description = "Dark theme for oxytail-loader"
license = "MIT"
version = "0.1.0"
edition = "2021"
rust-version = "1.74.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxytail-base = { path = "../oxytail-base"}
floem = { git = "https://github.com/lapce/floem", rev = "92ba6406b2406e4223933267137229db0a619a0a" }
